config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in:
    %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [*0..5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require('restaurant').permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container" style="margin-top: 50px">
  <div class="d-flex justify-content-between" style="margin-bottom: 10px">
  <h1>All restaurants</h1>
  <button type="button" class="btn btn-outline-primary"><%=link_to 'Create new', new_restaurant_path%></button>
  </div>

  <table class="table table-hover table-sm" style="width:1100px">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Address</th>
      <th>Category</th>
      <th>Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
    <tr>
      <th><%=restaurant.id%></th>
      <td><%=link_to restaurant.name, restaurant_path(restaurant)%></td>
      <td><%=restaurant.address%></td>
      <td><%=restaurant.category%></td>
      <td><%=restaurant.phone_number%></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/restaurants/new.html.erb
<div class="container" style="margin-top: 50px">
<h1>Create new restaurant</h1>
  <div style="width: 500px">
    <%= simple_form_for (@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :category, collection:%w[chinese italian japanese french belgian]%>
      <%= f.input :phone_number %>
      <%= f.submit "add a restaurant", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container" style="margin-top: 50px">
  <h1>Details</h1>

  <table class="table table-hover table-sm" style="width:1100px">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Address</th>
        <th>Category</th>
        <th>Phone</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th><%=@restaurant.id%></th>
        <td><%=@restaurant.name%></td>
        <td><%=@restaurant.address%></td>
        <td><%=@restaurant.category%></td>
        <td><%=@restaurant.phone_number%></td>
      </tr>
    </tbody>
  </table>

  <div style="margin-top: 50px;">
    <% @restaurant.reviews.each do |review|%>
      <div class="card border-secondary mb-3" style="max-width: 50rem;">
        <div class="card-header">Rating: <%= review.rating %> </div>
        <div class="card-body text-secondary">
          <p class="card-text"><%= review.content %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <button type="button" class="btn btn-outline-primary"><%=link_to 'Back to overview', restaurants_path%></button>
    <button type="button" class="btn btn-outline-primary"><%=link_to 'Create a review', new_restaurant_review_path(@restaurant)%></button>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container" style="margin-top: 50px">
<h1>Create new review</h1>
  <div style="width: 500px">
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection:%w[0 1 2 3 4 5]%>
      <%= f.submit "add review", class: "btn btn-primary" %>
    <% end %>
  </div>
  <button type="button" class="btn btn-outline-primary" style="margin-top: 50px"><%=link_to 'Back to overview', restaurants_path%></button>
</div>